In [2]:
import numpy as np
import pandas as pd

In [3]:
LANG = "en"
def select_lang(d):
    if pd.isna(d):
        return float("NaN")
    elif isinstance(d, dict):
        return d[LANG]
    elif isinstance(d, list):
        return select_lang(d[0])
    return d

In [4]:
meta = pd.read_json("../data/week_2022_01.json")
meta = meta.drop([
    "name", "color", "data", "xAxisValues", "format", "yAxis", "type", 
    "navigatorOptions", "hideInPercentView", "ignoreForTooltipSum",
    "visible", "showInLegend", "showInNavigator"], axis=1)
for col in ("y0AxisLabelPercent", "y1AxisLabel", "y1AxisLabelPercent", 
    "chartSubTitle", "chartTitle", "comment", "xAxisLabel", "y0AxisLabel"):
    meta[col] = meta[col].apply(select_lang)
meta = meta.loc[0]

meta["dateDownload"] = pd.to_datetime(meta["date"], unit="ms").tz_localize(meta["timeZone"])
meta = meta.drop("date")
meta

xAxisFormat                                                     unixTime
timeZone                                                             UTC
y0AxisDecimalPlaces                                                  1.0
showNavigator                                                        1.0
datasource             ENTSO-E, AGEE-Stat, Destatis, Fraunhofer ISE, ...
stacking                                           stacked_absolute_area
comment                Net generation of power plants for public powe...
xAxisLabel                                                          Date
y0AxisLabel                                                   Power (MW)
y0AxisLabelPercent                                             Power (%)
y1AxisLabel                                          Renewable share (%)
y1AxisLabelPercent                                   Renewable share (%)
y1AxisDecimalPlaces                                                  1.0
chartSubTitle                             Energetically corrected values
chartTitle             Public net electricity generation in Germany i...
dateDownload                         2022-12-03 13:32:44.284999936+00:00
Name: 0, dtype: object

In [5]:
column_info = pd.read_json("../data/week_2022_47.json")
column_info = column_info[["name", "color", "visible", "showInLegend", "showInNavigator", "yAxis"]]
column_info["name"] = column_info["name"].apply(select_lang)

column_info

,name,color,visible,showInLegend,showInNavigator,yAxis
0,Hydro pumped storage consumption,"rgb(50,50,150)",False,True,0.0,0
1,Import Balance,"rgb(125,25,125)",False,True,0.0,0
2,Nuclear,"rgb(255,0,0)",True,True,0.0,0
3,Hydro Run-of-River,"rgb(0,0,200)",True,True,0.0,0
4,Biomass,"rgb(0,150,50)",True,True,0.0,0
5,Fossil brown coal / lignite,"rgb(150,125,100)",True,True,0.0,0
6,Fossil hard coal,"rgb(50,50,50)",True,True,0.0,0
7,Fossil oil,"rgb(125,100,75)",True,True,0.0,0
8,Fossil gas,"rgb(250,150,75)",True,True,0.0,0
9,Geothermal,"rgb(50,50,150)",True,True,0.0,0
10,Hydro water reservoir,"rgb(175,200,255)",True,True,0.0,0
11,Hydro pumped storage,"rgb(0,150,225)",True,True,0.0,0
12,Others,"rgb(150,125,175)",True,True,0.0,0
13,Waste,"rgb(84, 48, 5)",True,True,0.0,0
14,Wind offshore,"rgb(155,175,145)",True,True,0.0,0
15,Wind onshore,"rgb(195,215,185)",True,True,0.0,0
16,Solar,"rgb(255,205,100)",True,True,0.0,0
17,Load,"rgb(50,50,50)",True,True,1.0,0
18,Residual load,"rgb(100,100,100)",False,True,0.0,0
19,Renewable share of generation,"rgb(120,170,255)",False,True,NaN,1
20,Renewable share of load,"rgb(251,128,114)",False,True,NaN,1

In [17]:
pd.DataFrame(np.vstack(df["data"]).T)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,-3645.8,-1362.2,3937.6,1434.0,5139.4,15006.3,8126.4,3.3,3355.0,18.7,...,96.0,44.3,1009.2,170.8,9876.7,0.0,43558.4,26377.4,35.6,39.4
1,-3696.8,-1060.1,3938.6,1434.1,5147.0,14967.0,8130.5,3.3,3362.5,18.7,...,95.3,44.3,1005.7,86.2,9943.6,0.0,43591.0,26450.6,35.6,39.3
2,-3705.1,-1031.5,3937.8,1436.5,5140.4,14968.6,8125.1,3.3,3354.1,18.7,...,95.3,44.4,1007.7,33.8,9893.3,0.0,43341.9,26296.9,35.4,39.3
3,-3827.6,-919.7,3937.5,1438.5,5137.4,14970.0,7985.3,3.3,3344.5,18.7,...,95.5,44.3,1003.6,19.1,9636.9,0.0,43182.1,26403.9,35.2,38.9
4,-4016.3,-378.8,3939.0,1443.9,5137.6,15005.0,7818.9,3.3,3321.1,18.7,...,95.2,44.4,1001.7,13.1,9413.6,0.0,42855.3,26303.9,35.0,38.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,-1914.9,-11020.6,3861.0,1408.9,5162.4,13210.1,7894.3,3.3,3809.9,18.7,...,67.4,35.4,1120.6,5002.9,17394.7,0.0,46929.6,17375.8,50.1,63.0
668,-2423.8,-10003.0,3804.9,1404.5,5154.1,13295.4,7246.3,3.3,3808.0,18.7,...,102.2,35.1,904.8,5131.8,17191.5,0.0,46415.1,16984.8,50.6,63.4
669,-2514.7,-9939.5,3712.2,1390.5,5139.4,13410.6,6987.1,3.3,3727.9,18.7,...,121.5,35.1,903.2,5168.3,17271.8,0.0,45799.3,16297.8,50.9,64.4
670,-2990.4,-9862.7,3687.7,1394.3,5143.4,13582.9,6895.1,3.3,3697.9,18.7,...,114.3,35.1,906.1,5130.0,17419.3,0.0,44600.5,14874.9,51.1,66.6
671,-3090.2,-9873.5,3690.3,1396.1,5131.3,13612.3,6721.9,3.3,3681.1,18.7,...,122.4,35.1,906.8,5142.6,17522.6,0.0,43856.7,14183.4,51.2,67.7

In [25]:
df = pd.read_json("../data/week_2022_47.json")
data = pd.DataFrame(np.vstack(df["data"]).T)
data.columns = df["name"].apply(select_lang).rename("Time")
data.index = pd.DatetimeIndex(pd.to_datetime(df.loc[0, "xAxisValues"], unit="ms")
data

Time,Hydro pumped storage consumption,Import Balance,Nuclear,Hydro Run-of-River,Biomass,Fossil brown coal / lignite,Fossil hard coal,Fossil oil,Fossil gas,Geothermal,...,Hydro pumped storage,Others,Waste,Wind offshore,Wind onshore,Solar,Load,Residual load,Renewable share of generation,Renewable share of load
2022-11-21 00:00:00,-3645.8,-1362.2,3937.6,1434.0,5139.4,15006.3,8126.4,3.3,3355.0,18.7,...,96.0,44.3,1009.2,170.8,9876.7,0.0,43558.4,26377.4,35.6,39.4
2022-11-21 00:15:00,-3696.8,-1060.1,3938.6,1434.1,5147.0,14967.0,8130.5,3.3,3362.5,18.7,...,95.3,44.3,1005.7,86.2,9943.6,0.0,43591.0,26450.6,35.6,39.3
2022-11-21 00:30:00,-3705.1,-1031.5,3937.8,1436.5,5140.4,14968.6,8125.1,3.3,3354.1,18.7,...,95.3,44.4,1007.7,33.8,9893.3,0.0,43341.9,26296.9,35.4,39.3
2022-11-21 00:45:00,-3827.6,-919.7,3937.5,1438.5,5137.4,14970.0,7985.3,3.3,3344.5,18.7,...,95.5,44.3,1003.6,19.1,9636.9,0.0,43182.1,26403.9,35.2,38.9
2022-11-21 01:00:00,-4016.3,-378.8,3939.0,1443.9,5137.6,15005.0,7818.9,3.3,3321.1,18.7,...,95.2,44.4,1001.7,13.1,9413.6,0.0,42855.3,26303.9,35.0,38.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-27 22:45:00,-1914.9,-11020.6,3861.0,1408.9,5162.4,13210.1,7894.3,3.3,3809.9,18.7,...,67.4,35.4,1120.6,5002.9,17394.7,0.0,46929.6,17375.8,50.1,63.0
2022-11-27 23:00:00,-2423.8,-10003.0,3804.9,1404.5,5154.1,13295.4,7246.3,3.3,3808.0,18.7,...,102.2,35.1,904.8,5131.8,17191.5,0.0,46415.1,16984.8,50.6,63.4
2022-11-27 23:15:00,-2514.7,-9939.5,3712.2,1390.5,5139.4,13410.6,6987.1,3.3,3727.9,18.7,...,121.5,35.1,903.2,5168.3,17271.8,0.0,45799.3,16297.8,50.9,64.4
2022-11-27 23:30:00,-2990.4,-9862.7,3687.7,1394.3,5143.4,13582.9,6895.1,3.3,3697.9,18.7,...,114.3,35.1,906.1,5130.0,17419.3,0.0,44600.5,14874.9,51.1,66.6
2022-11-27 23:45:00,-3090.2,-9873.5,3690.3,1396.1,5131.3,13612.3,6721.9,3.3,3681.1,18.7,...,122.4,35.1,906.8,5142.6,17522.6,0.0,43856.7,14183.4,51.2,67.7